### ISSUE TITLE
Error Pickling Large Files with Multiprocessing

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#102]
When analyzing an array of length 2**26 (67,108,864 data points) using DGX1/DGX2, @quasiben encountered the following error after 435 minutes of computation:

```
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    start_time = time.time()
  File "/datasets/bzaitlen/GitRepos/stumpy/stumpy/gpu_stump.py", line 543, in gpu_stump
    profile[idx], indices[idx] = result.get()
  File "/datasets/bzaitlen/miniconda3/envs/stumpy-10.1/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/datasets/bzaitlen/miniconda3/envs/stumpy-10.1/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/datasets/bzaitlen/miniconda3/envs/stumpy-10.1/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/datasets/bzaitlen/miniconda3/envs/stumpy-10.1/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

<s>From what could be gathered, this is an issue with `pickle` (used in `multiprocessing`) returning a (object) result back to the parent that is larger than 4GiB. It is important to note that this is **not** a problem with the input data being passed over into `multiprocessing` from parent to child. Instead, we should focus on the data being passed back from child to parent.</s> 

Additionally, this is independent of the GPU hardware (or number of GPUs as long as we are using `multiprocessing` with 2 or more GPUs). So, this error should be reproducible using a pair of 1080 Ti's with an array length of 2**26.

**Comment by seanlaw** [comment]
A few possible solutions:

1. Chunk the array(s) being returned from the child and reassemble them in the parent process.
2. Write the result to disk

**Comment by seanlaw** [comment]
It turns out that the best solution for this was to switch from multiprocessing to `threading`. This eliminates pickling altogether and it actually simplifies the code considerably!

**Comment by seanlaw** [comment]
We need a proper test case outside of STUMPY that creates a large array in the child process and see what happens. This way, we'll know where the limitations are (i.e., is the problem with the function inputs or the function outputs).

**Comment by seanlaw** [comment]
This problem is with BOTH the size of the inputs as well as the size of the outputs. Both are too big. We'll have to figure out the best way to write the data to disk without pickling.

**Comment by seanlaw** [comment]
This was fixed by replacing the pickling components with manual writing/reading of numpy arrays to file
