### ISSUE TITLE
TypeError: _array_equal_dispatcher() got an unexpected keyword argument 'equal_nan'

### ISSUE THREAD

**Issue by fanaee** [TDAmeritrade/stumpy#321]
Traceback (most recent call last):
  File "/home/stud1/h/hadfan20/.local/MPdemo.py", line 9, in <module>
    matrix_profile = stumpy.gpu_stump(your_time_series, m=window_size, device_id=all_gpu_devices)
  File "/home/stud/h/hadfan20/.local/lib/python3.8/site-packages/stumpy/gpu_stump.py", line 465, in gpu_stump
    if ignore_trivial and core.are_arrays_equal(T_A, T_B) is False:  # pragma: no cover
  File "/home/stud/h/hadfan20/.local/lib/python3.8/site-packages/stumpy/core.py", line 217, in are_arrays_equal
    return np.array_equal(a, b, equal_nan=True)
  File "<__array_function__ internals>", line 4, in array_equal
TypeError: _array_equal_dispatcher() got an unexpected keyword argument 'equal_nan'

**Comment by seanlaw** [comment]
@fanaee Thank you for reporting this. Can you try updating `numpy` to the latest version? This new `equal_nan` argument requires `numpy >= 1.19.0`

I will bump the minimum version in `setup.py` and push a patch

**Comment by seanlaw** [comment]
This is fixed in v1.7.1 now. Apologies for that!
