### ISSUE TITLE
Robust Time Series Chains

### ISSUE THREAD

**Issue by seanlaw** [TDAmeritrade/stumpy#730]
I just came across this new paper by Jessica Lin on a more [robust time series chain](https://arxiv.org/pdf/2211.02146.pdf). 

Not sure if it is relevant or how it compares with #211

**Comment by seanlaw** [comment]
The paper also states the following:

> The most closely related works are the ones by Zhu et al. [5] and Imamura et al. [6]. Zhu et al. [5] first introduce the concept of time series chains. The work enforces every adjacent pair of subsequences in the chain to be the left and right nearest neighbors of each other, and reports the longest chain as the top chain in the time series. Although the concept is simple and intuitive, the bi-directional nearest neighbor requirement is shown to be too strict in many real-world applications, as the chain can easily break by data fluctuations and noise [6]. Imamura et al. [6] relax the bi-direction condition by only enforcing the single-directional left nearest neighbor requirement, and added a pre-defined angle constraint to guarantee the directionality of the discovered chains. The concept is shown to be more robust than [5] in some conditions, but a new angle parameter is introduced, and we have observed that in some real-world scenarios, no meaningful chains can be found no matter how we set this parameter.

This is mostly consistent with what @NimaSarajpoor observed in his earlier explorations

**Comment by andersooi** [comment]
Hi! I see that this issue is a 'good first issue' and would like to see how I can help as a first-time contributor to this project

**Comment by NimaSarajpoor** [comment]
@andersooi 
Thanks for keeping your interest in contributing to this library! Since I contributed before to something similar (see #211), I thought it might be a good idea to provide my input, which is mostly based on the information provided by @seanlaw in [this comment](https://github.com/TDAmeritrade/stumpy/issues/211#issuecomment-844482828). 


* Try to make yourself familiar with the contribution process: See [Contributor's Guide](https://stumpy.readthedocs.io/en/latest/Contribute.html) 
* Personally, I prefer to understand the basic first. So, taking a look at [this notebook](https://github.com/TDAmeritrade/stumpy/blob/6971995a91c5c9ce9553af26792bfa9d1e39f934/docs/Tutorial_STUMPY_Basics.ipynb) might be helpful. 
* Start with creating a notebook `docs/Tutorial_robust_chains.ipynb`.  The goal is to see if two or more figures from the original paper, [robust time series chain](https://arxiv.org/pdf/2211.02146.pdf), can be reproduced based on the proposed algorithms. This notebook can be considered as a tutorial for the paper. For instance, see  [Time Series Chain](https://github.com/TDAmeritrade/stumpy/blob/6971995a91c5c9ce9553af26792bfa9d1e39f934/docs/Tutorial_Time_Series_Chains.ipynb) and [Time Series Geometric Chains](https://github.com/TDAmeritrade/stumpy/blob/6971995a91c5c9ce9553af26792bfa9d1e39f934/docs/Tutorial_Geometric_Chains.ipynb) You can follow a similar structure in your notebook. 
* Try to submit a PR as you make progress in your notebook rather than waiting till the very end when the whole notebook is complete. Pushing your commits that contain small changes can help reviewer follow your work more easily and provide more constructive feedback. As a side, for the sake of consistency, the name of variables should be similar to what exists in STUMPY's codebase. Maybe checkout the docstrings in `stumpy/stump.py` (and `stumpy/chains.py`) to make yourself familiar with some of the variables names.
* Eventually, a decision can be made to see if the notebook should be merged and if its functions should be moved to a `.py` files to create an API. 

I would be happy to help you along the way. Feel free to ask any questions you may have. 

----

@seanlaw 
Please provide any additional comments you may have as you certainly have better vision.

**Comment by andersooi** [comment]
Thanks @NimaSarajpoor for your insights! I will start by familiarising myself with the contribution guide and looking through the stumpy basics tutorial notebook first.

**Comment by seanlaw** [comment]
@andersooi This looks very familiar and I believe @joehiggi1758 had encountered this recently in issue https://github.com/TDAmeritrade/stumpy/issues/957#issuecomment-2128506321. Would it be possible to swithc to using `conda` instead? 

> Oh no! 💥 💔 💥
2387 files would be reformatted, 779 files would be left unchanged, 1 file would fail to reformat.
Error: Test execution encountered exit code 123

This is coming from `black` and, currently, it looks like `black` is looking (recursively) at files in your `root`/`home` directory rather than only in the cloned `stumpy` directory. Unfortunately, I don't use `.vnenv` and so it's not entirely clear to me why this is happening. I'm thinking that you may need to change directories into the cloned `stumpy` directory. Perhaps @JosephTLucas would be willing to provide some pointers here? Otherwise, we may need to remove the `venv` line from the Contributors Guide.

@andersooi What happens when you do

```
$ ./test.sh show
```

**Comment by andersooi** [comment]
Hi @seanlaw sorry for the late reply!

I took a look at the comment in the issue that you linked and it seems to be the same thing that I am facing. I already changed the directory to the cloned `stumpy` directory, but the issue persists.  I will try out using `conda` instead.

When I ran `./test.sh show`, this was the output:
```
(.venv) Anders@192 stumpy %  ./test.sh show 
Show development/test environment
Current working directory:  /Users/Anders_1/Desktop/Projects/stumpy
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'black'
Black version: 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'flake8'
Flake8 versoin: 
Python version:  3.11.4
NumPy version:  2.0.0
SciPy version:  1.14.0
Numba version:  0.60.0
```

**Comment by JosephTLucas** [comment]
Reading through this and #957 , I believe this is the issue:

1. Python `venv` creates a directory for all of the python dependencies. (FWIW, conda does something similar, but out in the user's home directory)
2. [test.sh](https://github.com/TDAmeritrade/stumpy/blob/0c45b772eba350d248b6b76c8ce05a68d5778587/test.sh#L58) doesn't exclude that directory when using `black` so black is executing against all of those virtual environment directories.

Since `.venv` is in the `.gitignore`, I think we just need to add `--extend-exclude` to the black command in `test.sh`. [Reference](https://black.readthedocs.io/en/stable/usage_and_configuration/file_collection_and_discovery.html#gitignore)

**Comment by seanlaw** [comment]
> When I ran ./test.sh show, this was the output:

This output shows that your environment doesn't have `black` installed and yet you were still able to run `./test.sh` 

> [UPDATE]:
Installed conda and created my virtual environment, ran ./conda.sh and ./setup.sh, both seemed fine. When I ran ./test.sh, got some ModuleNotFoundErrors for pytest, dask, distributed so went ahead and did conda install pytest dask distributed. 

That's REALLY strange. `./conda.sh` basically installs the packages listed in `environment.yml`, which contains `dask`, `distributed`, and `pytest` (via `pytest-cov`). Did you happen to notice any errors/warnings when you ran `./conda.sh`?

> Ran the test file again and got the following output:

@andersooi Can you please try running `test.sh` again and see if the tests still fail with the same error?

**Comment by seanlaw** [comment]
> Since .venv is in the .gitignore, I think we just need to add --extend-exclude to the black command in test.sh.

Thanks @JosephTLucas! I will investigate further

**Comment by andersooi** [comment]
> That's REALLY strange. `./conda.sh` basically installs the packages listed in `environment.yml`, which contains `dask`, `distributed`, and `pytest` (via `pytest-cov`). Did you happen to notice any errors/warnings when you ran `./conda.sh`?

So I deleted everything and tried again from the start. Running `./conda.sh` on the first time gave two PackageNotInstalledErrors:
```
PackageNotInstalledError: Package is not installed in prefix.
  prefix: /Users/Anders_1/opt/anaconda3/envs/stumpy-env
  package name: conda
```
and
```
PackageNotInstalledError: Package is not installed in prefix.                                                                                               
  prefix: /Users/Anders_1/opt/anaconda3/envs/stumpy-env
  package name: numpy
```

so I went ahead and ran `./conda.sh` again, and there weren't any warnings or errors.

> @andersooi Can you please try running `test.sh` again and see if the tests still fail with the same error?

This time, running `./test.sh` took a while, almost an hour - not too sure if it's supposed to be that long or maybe because I'm not working with a GPU, though I see a lot of repeated tests (I am guessing because they were skipped or something and the script is trying to test it again?)

Anyways, the tests eventually stopped and at the end, this was the message:
```
=================================================================== 21 passed in 18.39s ====================================================================
Ray Not Installed
Name    Stmts   Miss  Cover   Missing
-------------------------------------
TOTAL   14448      0   100%

86 files skipped due to complete coverage.
Cleaning Up
```

Here is a link to a pastecode link showing the entire test process: https://pastecode.io/s/fi7fguid

I'm guessing that I have to install Ray and try running `./test.sh` again? Though waiting for 1h for the entire tests to complete is rather long 😅

**Comment by seanlaw** [comment]
> PackageNotInstalledError: Package is not installed in prefix.

This error is rather strange but i'm glad that re-running `./conda.sh` fixed it (though it should have installed correctly the firs time if your environment was set up correctly). 

> so I went ahead and ran ./conda.sh again, and there weren't any warnings or errors.

Excellent!

> Anyways, the tests eventually stopped and at the end, this was the message:

This is a great sign. Note that we have two rounds of testing. The first one executes all unit tests using `numba` JIT-compiled functions and so this is expected to be fast. However, the second round of running the unit tests is for coverage testing and this will turn off all JIT compiling, which forces everything to be much slower.

You can run the fast unit tests by itself with `./test.sh unit` or the coverage tests by itself via `./test.sh coverage`. However, in this case, you'll be focused on creating a reproducible notebook (i.e., you aren't adding code to the code base... yet) so testing can be ignored for now.

> I'm guessing that I have to install Ray and try running ./test.sh again?

You can ignore `ray` completely

> Though waiting for 1h for the entire tests to complete is rather long 😅

I agree. I noticed this yesterday as well and I believe we know where the recent increase in time is coming from (see [this issue](https://github.com/TDAmeritrade/stumpy/issues/982#issuecomment-2224137251)). Of course, this is also dependent on the number of threads and the speed of those threads. We have over 1500 tests that need to be run but, to reiterate, this is not so important for trying to reproduce the robust time series chains and then possible consider it as a throwaway prototype from which to build off of if necessary. Does that make sense @andersooi?

**Comment by andersooi** [comment]
> This is a great sign. Note that we have two rounds of testing. The first one executes all unit tests using `numba` JIT-compiled functions and so this is expected to be fast. However, the second round of running the unit tests is for coverage testing and this will turn off all JIT compiling, which forces everything to be much slower.
> 
> You can run the fast unit tests by itself with `./test.sh unit` or the coverage tests by itself via `./test.sh coverage`. However, in this case, you'll be focused on creating a reproducible notebook (i.e., you aren't adding code to the code base... yet) so testing can be ignored for now.

Ahh, now I understand why there were repeated tests. This makes sense.

> I agree. I noticed this yesterday as well and I believe we know where the recent increase in time is coming from (see [this issue](https://github.com/TDAmeritrade/stumpy/issues/982#issuecomment-2224137251)). Of course, this is also dependent on the number of threads and the speed of those threads. We have over 1500 tests that need to be run but, to reiterate, this is not so important for trying to reproduce the robust time series chains and then possible consider it as a throwaway prototype from which to build off of if necessary. Does that make sense @andersooi?

Yup, thank you for the detailed explanations!

I have gone through the `Tutorial_STUMPY_Basics` notebook to familiarise myself with the basics, will proceed with creating the notebook.

Will reach out if I have any questions or run into any difficulties!

**Comment by seanlaw** [comment]
> I have gone through the Tutorial_STUMPY_Basics notebook to familiarise myself with the basics, will proceed with creating the notebook.

@andersooi Instead of the `Tutorial_STUMPY_Basics` notebook, I might recommend [this "work-in-progress" reproducer](https://github.com/TDAmeritrade/stumpy/pull/920) and its corresponding [notebook](https://app.reviewnb.com/TDAmeritrade/stumpy/pull/920/). The `Tutorial_STUMPY_Basics` notebook is already "polished" and the underlying code has already been converted into `stumpy` functions and pushed into the code base. However, the "dirtier" `damp` code example is still being iterated/debated upon and might provide a better perspective on the expectations (i.e., that we want to see all of the code and whether or not it actually "works" as well as claimed by the authors). If it turns out to be too brittle (or the results from the paper aren't reproducible) and it can't actually be general enough to be applied broadly to other use cases then we should avoid putting it into the hands of our users and abandon ship! This is essentially our due diligence phase.

**Comment by andersooi** [comment]
@seanlaw sure thing, I will give it a look!
